sudo: required

services:
  - docker

cache:
  directories:
    - out

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - apt list --installed
  - sudo apt-get purge -y --allow-remove-essential build-essential chromium-browser chromium-codecs-ffmpeg-extra cassandra cassandra-tools couchdb couchdb-bin couchdb-common elasticsearch mongodb-org mongodb-org-mongos mongodb-org-server mongodb-org-shell mongodb-org-tools mysql-client-5.6 mysql-client-core-5.6 mysql-common mysql-common-5.6 mysql-server-5.6 mysql-server-core-5.6 openjdk-7-jdk openjdk-7-jre openjdk-7-jre-headless openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless oracle-java8-installer oracle-java8-unlimited-jce-policy oracle-java9-installer oracle-java9-set-default oracle-java9-unlimited-jce-policy
  - sudo apt-get autoclean
  - sudo apt-get clean
  - sudo rm -rf /opt/* /usr/share/* /var/lib/mongodb /var/lib/mysql /var/lib/postgresql /usr/lib/google-cloud-sdk /usr/lib/riak /usr/lib/llvm-3.4 /usr/lib/postgresql /usr/local/clang-3.9.0 /usr/local/firefox-55.0.2 /usr/local/packer-1.0.2 /usr/local/gradle-4.0.1 /usr/local/phantomjs-1.9.8 /usr/local/phantomjs-2.0.0 /usr/local/heroku /usr/local/neo4j-3.2.1 /home/travis/.rvm /home/travis/.phpenv /home/travis/.nvm /home/travis/.gimme /lib/modules/4.4.0-81-generic
#  - (sudo du -h -d 2 /lib/modules) || echo 'ignore error'
#  - (sudo du -h -d 2 /var/lib) || echo 'ignore error'
#  - (sudo du -h -d 2 /usr/lib) || echo 'ignore error'
#  - (sudo du -h -d 2 /usr/local) || echo 'ignore error'
#  - (sudo du -h -d 2 /home/travis) || echo 'ignore error'
  - df -hT


install:
  - git ls-remote --tags https://chromium.googlesource.com/chromium/src.git > ./TAGS
  - cat ./TAGS | grep refs | cut -d/ -f3 | sort -rn | head -1 > ./VERSION
  - export LATEST_VERSION=`cat ./VERSION`
  - echo $LATEST_VERSION
  - export VERSION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo $LATEST_VERSION; else echo $TRAVIS_BRANCH ; fi`
  - echo $VERSION
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $TAG
  - export REPO=$TRAVIS_REPO_SLUG
  - echo $REPO
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

script:
  - ./prepare-or-build.sh

after_success:
  - docker images

