sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - apt list --installed
  - sudo apt-get purge -y --allow-remove-essential build-essential chromium-browser chromium-codecs-ffmpeg-extra cassandra cassandra-tools couchdb couchdb-bin couchdb-common elasticsearch mongodb-org mongodb-org-mongos mongodb-org-server mongodb-org-shell mongodb-org-tools mysql-client-5.6 mysql-client-core-5.6 mysql-common mysql-common-5.6 mysql-server-5.6 mysql-server-core-5.6 openjdk-7-jdk openjdk-7-jre openjdk-7-jre-headless openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless oracle-java8-installer oracle-java8-unlimited-jce-policy oracle-java9-installer oracle-java9-set-default oracle-java9-unlimited-jce-policy
   #  cloud-guest-utils cloud-init  emacs emacs23-bin-common emacs23-common emacs23-common-non-dfsg emacs23-nox emacs24 emacs24-bin-common emacs24-common emacs24-common-non-dfsg emacsen-common erlang-asn1 erlang-base erlang-corba erlang-crypto erlang-diameter erlang-edoc erlang-eldap erlang-erl-docgen erlang-eunit erlang-ic erlang-inets erlang-mnesia erlang-nox erlang-odbc erlang-os-mon erlang-parsetools erlang-percept erlang-public-key erlang-runtime-tools erlang-snmp erlang-ssh erlang-ssl erlang-syntax-tools erlang-tools erlang-webtool erlang-xmerl gcc gcc-4.8 gcc-4.8-base gcc-4.9-base gce-compute-image-packages mongodb-org mongodb-org-mongos mongodb-org-server mongodb-org-shell mongodb-org-tools mysql-client-5.6 mysql-client-core-5.6 mysql-common mysql-common-5.6 mysql-server-5.6 mysql-server-core-5.6 openjdk-7-jdk openjdk-7-jre openjdk-7-jre-headless openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless oracle-java8-installer oracle-java8-unlimited-jce-policy oracle-java9-installer oracle-java9-set-default oracle-java9-unlimited-jce-policy perl perl-base perl-modules postgresql-9.2 postgresql-9.2-postgis-2.3-scripts postgresql-9.3 postgresql-9.3-postgis-2.3-scripts postgresql-9.4 postgresql-9.4-postgis-2.3-scripts postgresql-9.5 postgresql-9.5-postgis-2.3-scripts postgresql-9.6 postgresql-9.6-postgis-2.3-scripts postgresql-client postgresql-client-9.2 postgresql-client-9.3 postgresql-client-9.4 postgresql-client-9.5 postgresql-client-9.6 postgresql-client-common postgresql-common postgresql-contrib-9.2 postgresql-contrib-9.3 postgresql-contrib-9.4 postgresql-contrib-9.5 postgresql-contrib-9.6 rabbitmq-server
  - sudo apt-get autoclean
  - sudo apt-get clean
  - sudo rm -rf /opt/* /usr/share/* /var/lib/mongodb /var/lib/mysql /var/lib/postgresql /usr/lib/google-cloud-sdk /usr/lib/riak /usr/lib/llvm-3.4 /usr/lib/postgresql /usr/local/clang-3.9.0 /usr/local/firefox-55.0.2 /usr/local/packer-1.0.2 /usr/local/gradle-4.0.1 /usr/local/phantomjs-1.9.8 /usr/local/phantomjs-2.0.0 /usr/local/heroku /usr/local/neo4j-3.2.1 /home/travis/.rvm /home/travis/.phpenv /home/travis/.nvm /home/travis/.gimme /lib/modules/4.4.0-81-generic
  - df -hT
  - git ls-remote --tags https://chromium.googlesource.com/chromium/src.git > ./TAGS
  - cat ./TAGS | grep refs | cut -d/ -f3 | sort -rn | head -1 > ./VERSION
  - export LATEST_VERSION=`cat ./VERSION`
  - echo $LATEST_VERSION
  - export VERSION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo $LATEST_VERSION; else echo $TRAVIS_BRANCH ; fi`
  - echo $VERSION
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $TAG
  - export REPO=$TRAVIS_REPO_SLUG
  - echo $REPO
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

install:
  - docker build -t ubuntu-build -t $REPO:build-${TAG} --build-arg CHROMIUM_VERSION=${VERSION} ubuntu-build
  - export CID=$(docker create ubuntu-build)
  - docker cp $CID:/root/chromium/headless.tar.gz debian
  - docker rm $CID
  - docker push $REPO

script:
  - docker build -t $REPO:$TAG debian

after_success:
  - docker images
  - docker push $REPO

